# Generated by Django 2.0.4 on 2018-04-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adesokanscrumy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumygoals',
            name='status',
            field=models.CharField(default='ok', max_length=20),
            preserve_default=False,
        ),
    ]
