# Generated by Django 2.0.4 on 2018-05-01 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adesokanscrumy', '0002_scrumygoals_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalstatus',
            name='status_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adesokanscrumy.GoalStatus'),
        ),
    ]
